import TopBar from "@/components/layout/TopBar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { inter } from "@/components/ui/typography";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Minhazur Rahaman Ratul - Official Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className={inter.className}>
        <TooltipProvider>
          <TopBar />
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
